"""Add room_no to InternshipApplication

Revision ID: e9f65d3b8d64
Revises: 55442da7a900
Create Date: 2025-03-07 14:39:22.408020

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9f65d3b8d64'
down_revision = '55442da7a900'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hostel', schema=None) as batch_op:
        batch_op.alter_column('hostel_type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               existing_nullable=True)

    with op.batch_alter_table('internship_application', schema=None) as batch_op:
        batch_op.add_column(sa.Column('room_no', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('internship_application', schema=None) as batch_op:
        batch_op.drop_column('room_no')

    with op.batch_alter_table('hostel', schema=None) as batch_op:
        batch_op.alter_column('hostel_type',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)

    # ### end Alembic commands ###
